services:
  fastapi:
    build:
      context: ./fastapi
    container_name: fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    # usa o .env que está DENTRO da pasta fastapi
    env_file:
      - ./fastapi/.env
    volumes:
      - ./fastapi:/app
    depends_on:
      - mlflow
      - thingsboard  # garante que o TB esteja subindo antes

  jupyter:
    build:
      context: ./notebooks
      dockerfile: Dockerfile
    container_name: jupyter
    ports:
      - "8889:8888"              # Jupyter em http://localhost:8889
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./data:/home/jovyan/data
    environment:
      JUPYTER_TOKEN: "mlproject"
    command: start-notebook.sh --NotebookApp.token='mlproject'

  # Postgres do ThingsBoard
  thingsboard-postgres:
    image: postgres:14
    container_name: thingsboard-postgres
    restart: always
    environment:
      POSTGRES_DB: thingsboard
      POSTGRES_USER: thingsboard
      POSTGRES_PASSWORD: thingsboard
    volumes:
      - tb_pgdata:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  thingsboard:
    image: thingsboard/tb-postgres:3.3.4
    container_name: thingsboard
    restart: always
    depends_on:
      - thingsboard-postgres
    ports:
      - "8080:9090"              # UI: http://localhost:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://thingsboard-postgres:5432/thingsboard
      SPRING_DATASOURCE_USERNAME: thingsboard
      SPRING_DATASOURCE_PASSWORD: thingsboard
    volumes:
      - thingsboard_data:/data
      - thingsboard_logs:/var/log/thingsboard

  # Postgres exclusivo do Trendz
  trendz-postgres:
    image: postgres:14
    container_name: trendz-postgres
    restart: always
    environment:
      POSTGRES_DB: trendz
      POSTGRES_USER: trendz
      POSTGRES_PASSWORD: trendz
    volumes:
      - trendz_pgdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"              # opcional: acessar o PG do Trendz pelo host

  mlflow:
    image: python:3.9-slim
    container_name: mlflow
    working_dir: /app
    restart: unless-stopped
    volumes:
      - ./mlruns:/app/mlruns      # precisa conter o experimento/modelo
    environment:
      MLFLOW_ENV_MANAGER: local
    ports:
      - "5001:5001"               # MLflow model server: http://localhost:5001
    command:
      - sh
      - -c
      - >
        pip install --no-cache-dir mlflow==3.1.4 scikit-learn &&
        mlflow models serve --env-manager local
        -m /app/mlruns/179780408009703120/models/m-c68ebe2764e942f6bc30316120f613c7/artifacts
        -h 0.0.0.0
        -p 5001

  trendz-python-executor:
    image: thingsboard/trendz-python-executor:1.14.0
    container_name: trendz-python-executor
    restart: always
    ports:
      - "8181:8181"
    environment:
      SCRIPT_ENGINE_RUNTIME_TIMEOUT: 30000
      EXECUTOR_MANAGER: 1
      EXECUTOR_SCRIPT_ENGINE: 6
      THROTTLING_QUEUE_CAPACITY: 10
      THROTTLING_THREAD_POOL_SIZE: 6
      NETWORK_BUFFER_SIZE: 10485760
    volumes:
      - trendz_executor_data:/python-executor

  trendz:
    image: thingsboard/trendz:1.14.0
    container_name: trendz
    restart: always
    depends_on:
      - thingsboard
      - trendz-postgres
      - trendz-python-executor
      - mlflow
    ports:
      - "8890:8888"              # Trendz UI: http://localhost:8890
    environment:
      # URL do ThingsBoard visto de dentro da rede Docker
      TB_API_URL: http://thingsboard:9090

      # Banco do Trendz
      SPRING_DATASOURCE_URL: jdbc:postgresql://trendz-postgres:5432/trendz
      SPRING_DATASOURCE_USERNAME: trendz
      SPRING_DATASOURCE_PASSWORD: trendz

      # Python Executor
      SCRIPT_ENGINE_PROVIDER: DOCKER_CONTAINER
      SCRIPT_ENGINE_DOCKER_PROVIDER_URL: trendz-python-executor:8181
      SCRIPT_ENGINE_TIMEOUT: 30000

    volumes:
      - trendz_data:/data
      - trendz_logs:/var/log/trendz

volumes:
  thingsboard_data:
  thingsboard_logs:
  tb_pgdata:
  trendz_pgdata:
  trendz_data:
  trendz_logs:
  trendz_executor_data:
