FROM jupyter/base-notebook

RUN pip install --no-cache-dir \
    pandas \
    numpy \
    matplotlib \
    seaborn \
    python-dotenv \
    snowflake-connector-python \
    snowflake-sqlalchemy \
    scikit-learn